---
title: "2112_CS130_final"
date: "12/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Initialization Cell
Here we load all the necessary libraries for the statistical analysis. 

```{r}
library(tidyverse)
library(haven)
library(dplyr)
library(PSweight)
library(rbounds)
library(ggplot2)
library(sensemakr)
```

##Data Loading + Cleaning
Bringing in the data and categorizing the ages into different treatment groups. 

```{r}

#I included males only here - but we will probable need to include females as well
#load the dataset available at ->
tare_data = read_dta("C:\\Users\\desot\\D\\CS130\\jprdata.dta")

tare_data <- data.frame(tare_data)
#Remove any Na values. 
tare_data <- na.omit(tare_data)

#Create 5 separate treatment groups based on the age categorizations from (McDoom, 2013)

tare_data <- tare_data %>% mutate(treat =
                     case_when(tare_data$age <=15 ~ 1,
                               tare_data$age <= 24 ~ 2, 
                               tare_data$age <= 34 ~ 3,
                               tare_data$age <= 44 ~ 4,
                               tare_data$age <= 94 ~ 5)
)

tare_data <- tare_data %>% mutate(gentreat = 
                                    case_when(tare_data$age <=24 ~ 0, 
                                              tare_data$age <= 94 ~ 1)
                                  )

tare_data

```

##Replication 

```{r}
#this cleans the data removing everyone above 15 and with an ethnicity of Hutu
clean_tare <- tare_data[tare_data$age >=15 & tare_data$ethnicity == 0 , ]

#the model that they developed 
logmodel <- glm(convicted ~ sex + age + age_squared + neighborhood_100m_targets + slope + distance_communitycenter + distance_mobilizer + neighborhood_100m_convicts + household_convicts + hhhead + household_size + interethnic_union + elevation + popdensity100m2, data = clean_tare, family = binomial)

#summary of the log model
summary(logmodel)

#Logs odd ratio of the model
exp(coefficients(logmodel))

```

##Creating the logistic model and conducting the sensitivity analysis
This is 

```{r}

#subsetted data removes any columns that we werent using in our regression analysis
subsetted_data <- subset(clean_tare, select = c(age, age_squared, neighborhood_100m_targets, convicted, sex, distance_communitycenter, distance_mobilizer, suspect, neighborhood_100m_convicts, neighborhood_100m_suspects, hhhead, household_convicts, household_suspects, household_size,  popdensity100m2, ethnicity))



#correlation to ensure none of the selected variables are co-linear 
tare_cor <- cor(subsetted_data, method = c("pearson"))

#model from above
logmodel2 <- glm(convicted ~ sex + age + age_squared + neighborhood_100m_targets + slope + distance_communitycenter + distance_mobilizer + neighborhood_100m_convicts + household_convicts + hhhead + household_size + interethnic_union + elevation + popdensity100m2, data = clean_tare)

#Chosen logistic model
convict1 <- glm(convicted ~ age_squared + popdensity100m2 + distance_communitycenter + distance_mobilizer + neighborhood_100m_convicts + neighborhood_100m_targets + household_convicts + hhhead, data = clean_tare, family = binomial)


convict2 <- lm(convicted ~ age_squared + popdensity100m2 + distance_communitycenter + distance_mobilizer + neighborhood_100m_convicts + neighborhood_100m_targets + household_convicts + hhhead, data = clean_tare)



sensitivity1 <- sensemakr(model = logmodel2, 
                         treatment = "neighborhood_100m_convicts",
                         benchmark_covariates = c("household_convicts"),
                         kd = 1:3)

sensitivity <- sensemakr(model = convict2, 
                         treatment = "neighborhood_100m_convicts",
                         benchmark_covariates = c("household_convicts", "hhhead"),
                         kd = 1:3)

summary(sensitivity1)
plot(sensitivity1)

summary(sensitivity)
plot(sensitivity)
#odds.ratio(convict, level = 0.95)
summary(convict2)
#exp(coefficients(convict))

summary(lm(convicted ~ household_convicts, data = clean_tare))
nrow(tare_data[tare_data$interethnic_union == 1,])

```


